version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /swagger.yml
      BASE_URL: /swagger
    volumes:
      - ./LWS-OpenAPI/swagger.yml:/swagger.yml
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  workaround:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: "bash -c 'cub kafka-ready -b kafka:29092 1 20 && kafka-topics --create --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1 --topic account.created'"
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testPassword
    container_name: "compose_mongo_runner"
    ports:
      - 27017

  kubernetes:
    image: rancher/k3s:latest
    environment:
      K3S_KUBECONFIG_OUTPUT: /output/kubeconfig.yml
      K3S_KUBECONFIG_MODE: 666
    volumes:
      - ./configurations:/output
    command: server --bind-address kubernetes
    privileged: true
    ports:
      - 6443
      - 80
      - 443

  lwsauth:
    build:
      context: ./LWS-Auth/.
      dockerfile: ./LWSAuthService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+
    volumes:
      - ./configurations/auth_config.json:/app/publish/appsettings.Development.json

  lwskube:
    depends_on:
      - workaround
      - kubernetes
    build:
      context: ./LWS-Kubernetes
      dockerfile: ./LWSKubernetesService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./configurations/kubeconfig.yml:/app/publish/kubeconfig.yml
      - ./configurations/kube_config.json:/app/publish/appsettings.Development.json
      - ./configurations/kube_config.json:/app/publish/appsettings.json
      - ./configurations/kubeconfig.yml:/root/.kube/config

  lwsgateway:
    depends_on:
      - lwsauth
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./configurations/nginx/test.conf:/etc/nginx/conf.d/default.conf