version: "3"
services:
  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /swagger.yml
      BASE_URL: /swagger
    volumes:
      - ./LWS-OpenAPI/swagger.yml:/swagger.yml

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: "rabbitmq_runner"
    ports:
      - "15672:15672"
      - "5672"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testPassword
    container_name: "compose_mongo_runner"
    ports:
      - 27017

  kubernetes:
    image: rancher/k3s:latest
    environment:
      K3S_KUBECONFIG_OUTPUT: /output/kubeconfig.yml
      K3S_KUBECONFIG_MODE: 666
    volumes:
      - ./configurations:/output
    command: server --bind-address kubernetes
    privileged: true
    ports:
      - 6443
      - 80
      - 443

  lwsauth:
    build:
      context: ./LWS-Auth/.
      dockerfile: ./LWSAuthService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+
    volumes:
      - ./configurations/auth_config.json:/app/publish/appsettings.Development.json

  lwskube:
    depends_on:
      kubernetes:
        condition: service_started
    build:
      context: ./LWS-Kubernetes
      dockerfile: ./LWSKubernetesService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./configurations/kubeconfig.yml:/app/publish/kubeconfig.yml
      - ./configurations/kube_config.json:/app/publish/appsettings.Development.json
      - ./configurations/kube_config.json:/app/publish/appsettings.json
      - ./configurations/kubeconfig.yml:/root/.kube/config

  lwsubuntu:
    build:
      context: ./LWS-Ubuntu/.
      dockerfile: ./LWSSandboxService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+
    volumes:
      - ./configurations/kubeconfig.yml:/app/publish/kubeconfig.yml
      - ./configurations/sandbox_config.json:/app/publish/appsettings.Development.json
      - ./configurations/sandbox_config.json:/app/publish/appsettings.json
      - ./configurations/kubeconfig.yml:/root/.kube/config

  lwsgateway:
    depends_on:
      - lwsauth
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./configurations/nginx/test.conf:/etc/nginx/conf.d/default.conf
      - ./configurations/nginx/location-global.conf:/etc/nginx/conf.d/location-global.conf
